[package]
name = "intent-api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
intent-core = { path = "../intent-core" }
intent-evm = { path = "../intent-evm" }

# Workspace deps
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
dotenv = { workspace = true }

# API-specific
axum = "0.8.8"
chrono = { version = "0.4.43", features = ["serde"] }
tower-http = { version = "0.6.8", features = ["cors"] }
